package input

//go:generate go run gen.go

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-01-29 18:31:24.961787 +0100 CET m=+0.001706143

func Day01() []int {
	return day01Values
}
